package com.mygdx.game.entity.message;

public enum GameMessageType {
	C2S_B2D_APPLY_FORCE,
	C2S_B2D_ADD_GAMEOBJECT,
	C2S_B2D_REMOVE_GAMEOBJECT,
	C2S_B2D_GET_GAMEOBJECT,
	C2S_B2D_GET_ALL_GAMEOBJECT,
	
	
	S2C_B2D_APPLY_FORCE,
	S2C_B2D_ADD_GAMEOBJECT,
	S2C_B2D_REMOVE_GAMEOBJECT,
	S2C_B2D_GET_GAMEOBJECT,
	S2C_B2D_GET_ALL_GAMEOBJECT;
	
	
}
